name: airhost_lint_plugin_bootstrap
version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  airhost_lint_plugin:
    git:
#      url: E:\Android\airhost\airhost_lint_plugin
      url: https://github.com/rex26/airhost_lint_plugin.git
